services:
  - type: worker
    name: codify-bot
    runtime: python
    rootDir: telegram-bot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: MANAGER_CHAT_ID
        sync: false
